### ISSUE TITLE
Waila compatibility

### ISSUE THREAD

**Issue by Kubimate** [BTW-Community/BTWMapMarkers#5]
Game crashes when using Waila (I'm on version 1.0.6) and pointing crosshair on a marker block.

```
java.lang.NullPointerException
	at net.minecraft.class_1071.<init>(class_1071.java:62)
	at mcp.mobius.waila.gui.BaseWindowGui.updateAchievementWindow(BaseWindowGui.java:67)
	at btw.community.waila.WailaAddon.checkKeybind(WailaAddon.java:76)
	at net.minecraft.class_399.handler$zzc000$updateAchievementWindow(class_399.java:522)
	at net.minecraft.class_399.method_1091(class_399.java:151)
	at net.minecraft.class_1600.method_2916(class_1600.java:1007)
	at net.minecraft.class_1600.run(class_1600.java:872)
	at java.lang.Thread.run(Unknown Source)
Stacktrace:
	at net.minecraft.class_478.method_4684(class_478.java:445)
	at net.minecraft.class_1600.method_2945(class_1600.java:2587)
	at net.minecraft.class_1600.run(class_1600.java:895)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by psychosledge** [comment]
Not familiar with that addon. When I get a chance, I will try to debug to see if there is something I can do about it.

**Comment by psychosledge** [comment]
I'm not sure what to do about this. If you want to debug waila with map markers loaded to see exactly what information is missing to cause the null exception, I would be happy to try and include a fix.

**Comment by psychosledge** [comment]
This may be fixed for the current release. It is only for BTW CE 3.x though
